language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode7.2 # clang 3.7
      compiler: clang
      env: COMPILER=clang
      before_install:
        - brew update
        - brew install pyenv
        - eval "$(pyenv init -)"
        - pyenv install 2.7.6
        - pyenv global 2.7.6
        - pyenv rehash
        - pip install cpp-coveralls
        - pyenv rehash
      after_success:
        - cd ..
        - make clean
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DJMESPATH_COVERAGE_INFO=ON
        - make unit
        - ./test/unit
        - coveralls --exclude test --exclude third_party --include src --gcov-options '\-lp'
    - os: osx
      osx_image: xcode6.4 # clang 3.6
      compiler: clang
      env: COMPILER=clang
    - os: osx
      osx_image: beta-xcode6.2 # clang 3.5
      compiler: clang
      env: COMPILER=clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake; fi

before_script:  
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cd test
  - ./unit
  - ./compliance
