language: cpp

dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'gcc-5']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=g++-5
        - export CMAKE_CC=gcc-5
        - cd jmespath.cpp
      env: COMPILER=g++-5
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'gcc-6']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=g++-6
        - export CMAKE_CC=gcc-6
        - cd jmespath.cpp
      env: COMPILER=g++-6
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'gcc-7', 'lcov']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=g++-7
        - export CMAKE_CC=gcc-7
        - cd jmespath.cpp
        - gem install coveralls-lcov
      after_success:
        - make clean
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DJMESPATH_COVERAGE_INFO=ON -DCMAKE_C_COMPILER=$CMAKE_CC -DCMAKE_CXX_COMPILER=$CMAKE_CXX
        - make unit
        - ./test/unit
        - cd ..
        - lcov --compat-libtool --directory . --capture --output-file coverage.info --no-external --gcov-tool $(which gcov-7)
        - lcov -r coverage.info -o coverage.info '*/third_party/*' '*/test/*'
        - coveralls-lcov coverage.info
      env: COMPILER=g++-7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'gcc-8']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=g++-8
        - export CMAKE_CC=gcc-8
        - cd jmespath.cpp
      env: COMPILER=g++-8
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['g++-6', 'clang-4.0']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=clang++-4.0
        - export CMAKE_CC=clang-4.0
        - cd jmespath.cpp
      env: COMPILER=clang++-4.0
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['g++-6', 'clang-5.0']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=clang++-5.0
        - export CMAKE_CC=clang-5.0
        - cd jmespath.cpp
      env: COMPILER=clang++-5.0
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['g++-6', 'clang-6.0']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=clang++-6.0
        - export CMAKE_CC=clang-6.0
        - cd jmespath.cpp
      env: COMPILER=clang++-6.0
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
          packages: ['g++-6', 'clang-7', 'python-pip', 'python-yaml']
      before_install:
        - cd ..
        - wget http://sourceforge.net/projects/boost/files/boost/1.65.1/boost_1_65_1.tar.bz2/download -O boost.tar.bz2
        - tar -xjf boost.tar.bz2
        - export BOOST_ROOT=$PWD/boost_1_65_1
        - wget https://github.com/nlohmann/json/archive/v3.4.0.tar.gz
        - tar -xf v3.4.0.tar.gz
        - cd json-3.4.0
        - mkdir build
        - cd build
        - cmake .. -DJSON_BuildTests=OFF
        - sudo make install
        - cd ../..
        - export CMAKE_CXX=clang++-7
        - export CMAKE_CC=clang-7
        - cd jmespath.cpp
      env: COMPILER=clang++-7
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      addons:
      homebrew:
        taps: ['nlohmann/json']
        packages: ['cmake', 'boost', 'nlohmann_json']
        update: true
      env: COMPILER=clang++
      env: CMAKE_CXX=clang++
      env: CMAKE_CC=clang
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      addons:
      homebrew:
        taps: ['nlohmann/json']
        packages: ['cmake', 'boost', 'nlohmann_json']
        update: true
      env: COMPILER=clang++
      env: CMAKE_CXX=clang++
      env: CMAKE_CC=clang
    - os: osx
      osx_image: xcode9
      compiler: clang
      addons:
      homebrew:
        taps: ['nlohmann/json']
        packages: ['cmake', 'boost', 'nlohmann_json']
        update: true
      env: COMPILER=clang++
      env: CMAKE_CXX=clang++
      env: CMAKE_CC=clang

before_script:  
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=$CMAKE_CC -DCMAKE_CXX_COMPILER=$CMAKE_CXX ..

script:
  - make
  - cd test
  - ./unit
  - ./compliance
  - cd ..
  - sudo make install
  - cd ../example
  - mkdir build;cd build
  - cmake -DCMAKE_C_COMPILER=$CMAKE_CC -DCMAKE_CXX_COMPILER=$CMAKE_CXX ..
  - make 
  - ./example
  - cd ../../build
