version: '{build}'
os: Visual Studio 2017
install:
- cmd: >-
    git submodule init

    git submodule update
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake -Wno-dev -G"Visual Studio 15 2017" ..

    cmake --build . --config Release
test_script:
- cmd: >-
    cd test

    Release\unit.exe

    Release\compliance.exe

    cd ..\..\example

    mkdir build & cd build

    cmake -G"Visual Studio 15 2017" ..

    cmake --build . --config Release

    Release\example.exe
    