version: '{build}'
os: Visual Studio 2017
install:
- cmd: >-
    git submodule init

    git submodule update

    set "BOOST_ROOT=C:\Libraries\boost_1_65_1"

    appveyor DownloadFile https://github.com/nlohmann/json/archive/v3.4.0.zip

    7z x v3.4.0.zip

    cd json-3.4.0

    mkdir build

    cd build

    cmake .. -DJSON_BuildTests=OFF -G"Visual Studio 15 2017"

    cmake --build . --target install

    cd ../..

build_script:
- cmd: >-
    mkdir build

    cd build

    cmake -Wno-dev -G"Visual Studio 15 2017" ..

    cmake --build . --config Release

    cmake --build . --target install --config Release

test_script:
- cmd: >-
    cd test

    Release\unit.exe

    Release\compliance.exe

    cd ..\..\example

    mkdir build & cd build

    cmake -G"Visual Studio 15 2017" ..

    cmake --build . --config Release

    Release\example.exe
    